drop table if exists tasks;

create table if not exists tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50),
    description VARCHAR(500),
    task_status VARCHAR(50),
    duration BIGINT,
    execution_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tasks PRIMARY KEY(id)
);
